---
driver:
  name: podman
platforms:
  - name: ubuntu-2204
    image: docker.io/ubuntu:22.04
    command: sleep infinity
    privileged: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      ubuntu-2204:
        ansible_user: root
        ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
dependency:
  name: galaxy
  enabled: false
